# 纹理名称, 纹理类型, 纹理参数
# 纹理名称应该是唯一的, 可以在材质定义中引用
textures = [
    ["tex-earth",   "image", "assets/earthmap.jpg"],    # "image"表示图片纹理, 参数为文件路径
    ["tex-face",    "image", "assets/awesomeface.jpg"],
    ["tex-board",   "image", "assets/board.jpg"],
]

# 材质名称, 材质类型, 是否使用纹理, 若是则提供纹理名称, 否则提供材质参数
# 材质名称应该是唯一的, 可以在物体定义中引用
# lambertian: [name, "lambertian", true, "tex-name"] OR [name, "lambertian", false, r, g, b]
# metal: [name, "metal", true, "tex-name", roughness] OR [name, "metal", false, r, g, b, roughness]
# dielectric: [name, "dielectric", false, ref_idx]
# light: [name, "light", false, r, g, b]
# pbr: [name, "pbr", true, "tex-name", metalic, roughness] OR [name, "pbr", false, r, g, b, metalic, roughness]
materials = [
    ["mat-light-white",     "light",        false,  2, 2, 2],
    ["mat-liquid",          "dielectric",   false,  1.5],
    ["mat-pbr-rough-rice",  "pbr",          false,  0.96, 0.96, 0.86, 0.01, 0.99],
    ["mat-pbr-metalic-red", "pbr",          false,  1.00, 0.00, 0.00, 0.80, 0.40],
    ["mat-pbr-rough-green", "pbr",          false,  0.00, 1.00, 0.00, 0.01, 0.99],
    ["mat-pbr-mirror",      "pbr",          false,  1.00, 1.00, 1.00, 0.99, 0.01],
    ["mat-pbr-rough-earth", "pbr",          true,   "tex-earth",      0.20, 0.20],
]

# 球心x,y,z坐标, 球半径, 材质名称
spheres = [
    [0, 10, -10, 20, "mat-pbr-rough-earth"], # 地球
    [-20, -20, 10, 10, "mat-liquid"],      # 透射
    # [35, -35, -35, 15, "mat-metal-silver"], # 镜面
    # [0, -10, 30, 5, "mat-liquid"],
    # [0, -10, 30, -4.9, "mat-liquid"], # 使用负半径, 和上一个球面一起组成一个透明气泡
]

# 矩形定义: 一个顶点+两条正交边+材质名称, 两条边分别被用作纹理映射的uv方向
# 下例中第一个矩形有一个顶点在(-50,50,-50), 此顶点处的两条边向量分别为(100,0,0)和(0,0,100), 且第一条边用作纹理映射的u方向
rectangles = [
    # "屋子"+顶部光照
    [[-50, 50, -50], [100, 0, 0], [0, 0, 100], "mat-pbr-rough-rice"], # 顶面
    [[-40, 49.9, -40], [80, 0, 0], [0, 0, 80], "mat-light-white"], # 顶光
    [[-50, 50, -50], [100, 0, 0], [0, -100, 0], "mat-pbr-rough-rice"], # 前面
    [[-50, 50, -50], [0, -100, 0], [0, 0, 100], "mat-pbr-metalic-red"], # 左侧面
    [[50, 50, -50], [0, -100, 0], [0, 0, 100], "mat-pbr-rough-green"], # 右侧面
    [[-50, -50, -50], [100, 0, 0], [0, 0, 100], "mat-pbr-mirror"], # 底面
]

# [true, path] OR [false, r, g, b]
# envlight = [true, "assets/envlight_town.jpg"] # 背景图片
envlight = [false, 0.0, 0.0, 0.0]

[canvas]
width = 1024             # 图片宽度
height = 1024            # 图片高度
# width = 256
# height = 256

[options]
samples_per_pixel = 4096 # 每个像素的采样数
max_depth = 5         # 递归的最大层数
use_bvh = true          # 是否使用bvh加速
parallel = true         # 是否并行渲染

[camera]
lookfrom = [0, 0, 50]    # 相机位置
lookat = [0, 0, 0]     # 焦点
vup = [0, 1, 0]         # 相机上方向
aperture = 0.0          # 相机"孔径", 孔径越大场景越模糊
vfov = 90               # 竖直方向的视角, 角度值
