# 纹理名称, 纹理类型, 纹理参数
# 纹理名称应该是唯一的, 可以在材质定义中引用
textures = [
    ["earth", "image", "../assets/earthmap.jpg"],   # 图片路径
    ["ground", "solid", 0.872, 0.66, 0.128], # 纯色纹理
]

# 材质名称, 材质类型, 是否使用纹理, 若是则提供纹理名称, 否则提供材质参数
# 材质名称应该是唯一的, 可以在物体定义中引用
materials = [
    ["mat-ground", "lambertian", true, "ground"],
    ["mat1", "dielectric", false, 1.5],    # 折射率
    ["mat2", "lambertian", true, "earth"],
    ["mat3", "metal", false, 0.6, 0.2, 0.8, 0.1],  # 对rgb三色的反射率, 模糊程度
]

# 球心x,y,z坐标, 球半径, 材质名称
spheres = [
    [0, -100.4, 0, 100, "mat-ground"],
    [-1, 0, -1, 0.4, "mat1"],
    # [-1, 0, -1, -0.45, "mat1"],
    [0, 0, -1, 0.4, "mat2"],
    [1, 0, -1, 0.4, "mat3"],
]

[canvas]
width = 600             # 图片宽度
height = 400            # 图片高度

[options]
samples_per_pixel = 100 # 每个像素的采样数
max_depth = 50         # 递归的最大层数
use_bvh = true          # 是否使用bvh加速
parallel = true         # 是否并行渲染

[camera]
lookfrom = [2, 2, 3]    # 相机位置
lookat = [0, 0, -1]     # 焦点
vup = [0, 1, 0]         # 相机上方向
aperture = 0.2          # 相机"孔径", 孔径越大场景越模糊
vfov = 20               # 竖直方向的视角, 角度值
