# 纹理名称, 纹理类型, 纹理参数
# 纹理名称应该是唯一的, 可以在材质定义中引用
textures = [
    ["red", "solid", 1, 0, 0],
    ["green", "solid", 0, 1, 0],
    ["blue", "solid", 0, 0, 1],
    ["black", "solid", 0, 0, 0],
    ["cyan", "solid", 0, 1, 1]
]

# 材质名称, 材质类型, 是否使用纹理, 若是则提供纹理名称, 否则提供材质参数
# 材质名称应该是唯一的, 可以在物体定义中引用
materials = [
    ["mat1", "lambertian", true, "red"],
    ["mat2", "metal", true, "green", 0],
    ["mat3", "metal", true, "blue", 0],
    ["mat4", "metal", true, "black", 0],
    ["ground", "lambertian", true, "cyan"],
]

# 球心x,y,z坐标, 球半径, 材质名称
spheres = [
    [0, -101, 0, 100, "ground"],
]

# 三角形顶点+纹理顶点、材质
triangles = [
    [[-1, -1, -2, 0, 0], [+1, -1, -2, 0, 0], [0, 1, -2, 0, 0], "mat1"],     # 底面
    [[+0, +0, -1, 0, 0], [-1, -1, -2, 0, 0], [1, -1, -2, 0, 0], "mat2"],      # 下侧面
    [[+0, +0, -1, 0, 0], [+1, -1, -2, 0, 0], [0, 1, -2, 0, 0], "mat3"],       # 右侧面
    [[+0, +0, -1, 0, 0], [-1, -1, -2, 0, 0], [0, 1, -2, 0, 0], "mat4"],       # 左侧面
]

[canvas]
width = 300             # 图片宽度
height = 200            # 图片高度

[options]
samples_per_pixel = 500 # 每个像素的采样数
max_depth = 100         # 递归的最大层数
use_bvh = true          # 是否使用bvh加速
parallel = true         # 是否并行渲染

[camera]
lookfrom = [0, 0, -0.5]    # 相机位置
lookat = [0, 0, -1]     # 焦点
vup = [0, 1, 0]         # 相机上方向
aperture = 0.0          # 相机"孔径", 孔径越大场景越模糊
vfov = 90               # 竖直方向的视角, 角度值
