# 纹理名称, 纹理类型, 纹理参数
# 纹理名称应该是唯一的, 可以在材质定义中引用
textures = [
    ["red", "solid", 1, 0, 0],
    ["silver", "solid", 0.72, 0.72, 0.72],
    ["gray", "solid", 0.5, 0.5, 0.5],
]

# 材质名称, 材质类型, 是否使用纹理, 若是则提供纹理名称, 否则提供材质参数
# 材质名称应该是唯一的, 可以在物体定义中引用
materials = [
    ["mat1", "lambertian", true, "red"],
    ["mat2", "metal", true, "red", 0],
    ["mat3", "metal", true, "silver", 0.01],
    ["mat4", "lambertian", true, "gray"],
]

# 球心x,y,z坐标, 球半径, 材质名称
spheres = [
]

# 三角面片模型路线, 材质(只支持纯色材质)
meshes = [
    ["../assets/bun_zipper_res4.ply", "mat4"],
]

[canvas]
width = 600             # 图片宽度
height = 400            # 图片高度

[options]
samples_per_pixel = 500 # 每个像素的采样数
max_depth = 100         # 递归的最大层数
use_bvh = true          # 是否使用bvh加速
parallel = true         # 是否并行渲染

[camera]
lookfrom = [0, 0.1, 0.5]    # 相机位置
lookat = [0, 0.1, -1]     # 焦点
vup = [0, 1, 0]         # 相机上方向
aperture = 0.0          # 相机"孔径", 孔径越大场景越模糊
vfov = 20               # 竖直方向的视角, 角度值
